export enum ProjectPermissionEnum {
  'Session Access' = 'session_access',
  'Users List Access' = 'user_list_access',
  'Exhibitor List Access' = 'exhibitor_list_access',
  'Allow Chat' = 'allow_chat',
  'Allow Meeting Requests' = 'allow_meeting_requests',
  'Limit Meeting Slots' = 'limit_meeting_slots',
  'Create Surveys and Communications' = 'create_survey_and_communications',
  'Receive In-App Support' = 'receive_in_app_support',
  'Show QR Code' = 'show_qr_code',
  'Scan QR Code' = 'scan_qr_code',
  'Post Creation' = 'post_creation',
  'Enable Agenda' = 'enable_agenda',
  'Simultaneous Agenda Limit' = 'simultaneous_agenda_limit',
  'Total Meeting Slots' = 'total_meeting_slots',
  'Allow Exhibitor Managers' = 'allow_exhibitor_manager',
  'Max Number of Managers Allow' = 'max_managers_allowed',
  'Enable Product Listing' = 'enable_product_listing',
  'Product Limit' = 'product_limit',
  'Can Manage Agenda' = 'can_manage_agenda',
  'Can Invite Managers' = 'can_invite_managers',
  'Can Edit Other Manager Permissions' = 'can_edit_other_manager_permission',
}
